export const result = {
  header: {
    uri: 'https://api.os.uk/search/places/v1/find?query=forest%20dene%20northwich',
    query: 'query=forest dene northwich',
    offset: 0,
    totalresults: 109974,
    format: 'JSON',
    dataset: 'DPA',
    lr: 'EN,CY',
    maxresults: 100,
    matchprecision: 1,
    epoch: '120',
    lastupdate: '2025-10-13',
    output_srs: 'EPSG:27700'
  },
  results: [
    {
      DPA: {
        UPRN: '200003232010',
        UDPRN: '6132431',
        ADDRESS: 'FOREST DENE, FOREST HILL, HARTFORD, NORTHWICH, CW8 2AT',
        BUILDING_NAME: 'FOREST DENE',
        THOROUGHFARE_NAME: 'FOREST HILL',
        DEPENDENT_LOCALITY: 'HARTFORD',
        POST_TOWN: 'NORTHWICH',
        POSTCODE: 'CW8 2AT',
        RPC: '1',
        X_COORDINATE: 361852.0,
        Y_COORDINATE: 371487.0,
        STATUS: 'APPROVED',
        LOGICAL_STATUS_CODE: '1',
        CLASSIFICATION_CODE: 'RD02',
        CLASSIFICATION_CODE_DESCRIPTION: 'Detached',
        LOCAL_CUSTODIAN_CODE: 665,
        LOCAL_CUSTODIAN_CODE_DESCRIPTION: 'CHESHIRE WEST AND CHESTER',
        COUNTRY_CODE: 'E',
        COUNTRY_CODE_DESCRIPTION: 'This record is within England',
        POSTAL_ADDRESS_CODE: 'D',
        POSTAL_ADDRESS_CODE_DESCRIPTION: 'A record which is linked to PAF',
        BLPU_STATE_CODE: '2',
        BLPU_STATE_CODE_DESCRIPTION: 'In use',
        TOPOGRAPHY_LAYER_TOID: 'osgb1000035905836',
        WARD_CODE: 'E05012219',
        PARISH_CODE: 'E04012543',
        PARENT_UPRN: '10011719253',
        LAST_UPDATE_DATE: '24/04/2019',
        ENTRY_DATE: '04/09/2002',
        BLPU_STATE_DATE: '15/11/2007',
        LANGUAGE: 'EN',
        MATCH: 0.5,
        MATCH_DESCRIPTION: 'NO MATCH',
        DELIVERY_POINT_SUFFIX: '1J'
      }
    },
    {
      DPA: {
        UPRN: '10006510253',
        UDPRN: '13787372',
        ADDRESS: 'FOREST DENE, EAGLE MOOR, LINCOLN, LN6 9DP',
        BUILDING_NAME: 'FOREST DENE',
        DEPENDENT_LOCALITY: 'EAGLE MOOR',
        POST_TOWN: 'LINCOLN',
        POSTCODE: 'LN6 9DP',
        RPC: '1',
        X_COORDINATE: 488846.0,
        Y_COORDINATE: 368028.0,
        STATUS: 'APPROVED',
        LOGICAL_STATUS_CODE: '1',
        CLASSIFICATION_CODE: 'RD02',
        CLASSIFICATION_CODE_DESCRIPTION: 'Detached',
        LOCAL_CUSTODIAN_CODE: 2520,
        LOCAL_CUSTODIAN_CODE_DESCRIPTION: 'NORTH KESTEVEN',
        COUNTRY_CODE: 'E',
        COUNTRY_CODE_DESCRIPTION: 'This record is within England',
        POSTAL_ADDRESS_CODE: 'D',
        POSTAL_ADDRESS_CODE_DESCRIPTION: 'A record which is linked to PAF',
        BLPU_STATE_CODE: '2',
        BLPU_STATE_CODE_DESCRIPTION: 'In use',
        TOPOGRAPHY_LAYER_TOID: 'osgb1000026613592',
        WARD_CODE: 'E05014441',
        PARISH_CODE: 'E04005802',
        LAST_UPDATE_DATE: '02/03/2019',
        ENTRY_DATE: '16/12/2003',
        BLPU_STATE_DATE: '09/07/2009',
        LANGUAGE: 'EN',
        MATCH: 0.4,
        MATCH_DESCRIPTION: 'NO MATCH',
        DELIVERY_POINT_SUFFIX: '1A'
      }
    },
    {
      DPA: {
        UPRN: '100060115799',
        UDPRN: '20267855',
        ADDRESS: 'FOREST DENE, WYCH CROSS, FOREST ROW, RH18 5JN',
        BUILDING_NAME: 'FOREST DENE',
        DEPENDENT_LOCALITY: 'WYCH CROSS',
        POST_TOWN: 'FOREST ROW',
        POSTCODE: 'RH18 5JN',
        RPC: '2',
        X_COORDINATE: 542820.56,
        Y_COORDINATE: 131070.66,
        STATUS: 'APPROVED',
        LOGICAL_STATUS_CODE: '1',
        CLASSIFICATION_CODE: 'RD02',
        CLASSIFICATION_CODE_DESCRIPTION: 'Detached',
        LOCAL_CUSTODIAN_CODE: 1435,
        LOCAL_CUSTODIAN_CODE_DESCRIPTION: 'WEALDEN',
        COUNTRY_CODE: 'E',
        COUNTRY_CODE_DESCRIPTION: 'This record is within England',
        POSTAL_ADDRESS_CODE: 'D',
        POSTAL_ADDRESS_CODE_DESCRIPTION: 'A record which is linked to PAF',
        BLPU_STATE_CODE: '2',
        BLPU_STATE_CODE_DESCRIPTION: 'In use',
        TOPOGRAPHY_LAYER_TOID: 'osgb1000006967575',
        WARD_CODE: 'E05011634',
        PARISH_CODE: 'E04003837',
        LAST_UPDATE_DATE: '24/04/2021',
        ENTRY_DATE: '03/05/2001',
        BLPU_STATE_DATE: '07/09/2007',
        LANGUAGE: 'EN',
        MATCH: 0.4,
        MATCH_DESCRIPTION: 'NO MATCH',
        DELIVERY_POINT_SUFFIX: '1N'
      }
    },
    {
      DPA: {
        UPRN: '100091247570',
        UDPRN: '53973575',
        ADDRESS: 'FOREST DENE, FOREST TERRACE, HIGH ROAD, CHIGWELL, IG7 5BW',
        BUILDING_NAME: 'FOREST DENE',
        DEPENDENT_THOROUGHFARE_NAME: 'FOREST TERRACE',
        THOROUGHFARE_NAME: 'HIGH ROAD',
        POST_TOWN: 'CHIGWELL',
        POSTCODE: 'IG7 5BW',
        RPC: '1',
        X_COORDINATE: 543059.0,
        Y_COORDINATE: 192310.0,
        STATUS: 'APPROVED',
        LOGICAL_STATUS_CODE: '1',
        CLASSIFICATION_CODE: 'RD02',
        CLASSIFICATION_CODE_DESCRIPTION: 'Detached',
        LOCAL_CUSTODIAN_CODE: 1535,
        LOCAL_CUSTODIAN_CODE_DESCRIPTION: 'EPPING FOREST',
        COUNTRY_CODE: 'E',
        COUNTRY_CODE_DESCRIPTION: 'This record is within England',
        POSTAL_ADDRESS_CODE: 'D',
        POSTAL_ADDRESS_CODE_DESCRIPTION: 'A record which is linked to PAF',
        BLPU_STATE_CODE: '2',
        BLPU_STATE_CODE_DESCRIPTION: 'In use',
        TOPOGRAPHY_LAYER_TOID: 'osgb1000001806748797',
        WARD_CODE: 'E05015729',
        PARISH_CODE: 'E04004039',
        LAST_UPDATE_DATE: '29/06/2022',
        ENTRY_DATE: '16/04/2001',
        BLPU_STATE_DATE: '16/04/2001',
        LANGUAGE: 'EN',
        MATCH: 0.4,
        MATCH_DESCRIPTION: 'NO MATCH',
        DELIVERY_POINT_SUFFIX: '1X'
      }
    },
    {
      DPA: {
        UPRN: '100060107548',
        UDPRN: '24605177',
        ADDRESS: '9, FOREST DENE, CROWBOROUGH, TN6 2HB',
        BUILDING_NUMBER: '9',
        THOROUGHFARE_NAME: 'FOREST DENE',
        POST_TOWN: 'CROWBOROUGH',
        POSTCODE: 'TN6 2HB',
        RPC: '2',
        X_COORDINATE: 553625.0,
        Y_COORDINATE: 130056.0,
        STATUS: 'APPROVED',
        LOGICAL_STATUS_CODE: '1',
        CLASSIFICATION_CODE: 'RD06',
        CLASSIFICATION_CODE_DESCRIPTION:
          'Self Contained Flat (Includes Maisonette / Apartment)',
        LOCAL_CUSTODIAN_CODE: 1435,
        LOCAL_CUSTODIAN_CODE_DESCRIPTION: 'WEALDEN',
        COUNTRY_CODE: 'E',
        COUNTRY_CODE_DESCRIPTION: 'This record is within England',
        POSTAL_ADDRESS_CODE: 'D',
        POSTAL_ADDRESS_CODE_DESCRIPTION: 'A record which is linked to PAF',
        BLPU_STATE_CODE: '2',
        BLPU_STATE_CODE_DESCRIPTION: 'In use',
        TOPOGRAPHY_LAYER_TOID: 'osgb1000000365578',
        WARD_CODE: 'E05011629',
        PARISH_CODE: 'E04003835',
        LAST_UPDATE_DATE: '24/04/2021',
        ENTRY_DATE: '03/05/2001',
        BLPU_STATE_DATE: '07/09/2007',
        LANGUAGE: 'EN',
        MATCH: 0.4,
        MATCH_DESCRIPTION: 'NO MATCH',
        DELIVERY_POINT_SUFFIX: '2S'
      }
    }
  ]
}
