name: Test Documentation Generation

on:
  pull_request:
    branches:
      - this-branch-does-not-exist-so-trigger-never-fires
  
  workflow_dispatch:
    inputs:
      branch_type:
        description: 'Type of branch to simulate'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - release/v1
          - release/v2

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-docs-generation:
    runs-on: ubuntu-latest
    environment:
      name: github-pages-test
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Generate documentation
        run: |
          bash .github/scripts/docs/generate-and-publish-docs.sh "${{ github.event.inputs.branch_type }}" "1.2.3"
          
          # Move to Jekyll expected structure
          mkdir -p _site
          cp -r docs-site/* _site/
          
          # Create .nojekyll file to bypass Jekyll processing
          touch _site/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4