name: Test Documentation Generation

on:
  workflow_dispatch:
    inputs:
      branch_type:
        description: 'Type of branch to simulate'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - release/v1
          - release/v2
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-docs-generation:
    runs-on: ubuntu-latest
    environment:
      name: github-pages-test
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install dependencies
        run: npm ci

      - name: Set branch type based on trigger
        id: set-branch
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "BRANCH_TYPE=${{ github.event.inputs.branch_type }}" >> $GITHUB_ENV
          else
            echo "BRANCH_TYPE=main" >> $GITHUB_ENV
          fi
          echo "VERSION=1.2.3" >> $GITHUB_ENV

      - name: Generate documentation
        run: |
          mkdir -p .github/scripts/docs
          bash .github/scripts/docs/generate-and-publish-docs.sh "$BRANCH_TYPE" "$VERSION"

      - name: Create Jekyll source directory
        run: |
          # Create Jekyll source directory
          mkdir -p site-src
          
          # First, copy all docs to site-src
          cp -r docs/* site-src/

      - name: Generate schema documentation
        run: |
          echo "🔄 Generating schema documentation..."
          node scripts/generate-schema-docs.js

      - name: Process schema documentation and prepare for Jekyll
        run: |
          echo "🔄 Processing documentation files..."
          chmod +x .github/scripts/docs/process-docs.sh
          .github/scripts/docs/process-docs.sh

      - name: Fix documentation links
        run: |
          echo "🔄 Fixing documentation links..."
          chmod +x .github/scripts/docs/fix-schema-links.sh
          .github/scripts/docs/fix-schema-links.sh

      - name: Create Jekyll configuration
        run: |
          echo "🔄 Creating Jekyll configuration files..."
          chmod +x .github/scripts/docs/create-jekyll-config.sh
          .github/scripts/docs/create-jekyll-config.sh

      - name: Build and verify Jekyll site
        run: |
          # Build the site
          echo "🔨 Building Jekyll site..."
          cd site-src
          bundle install
          JEKYLL_ENV=production bundle exec jekyll build --verbose --destination ../_site
          cd ..
          
          # Fix capitalization issues
          echo "🔧 Fixing case sensitivity issues..."
          if [ -f "_site/INDEX.html" ] && [ ! -f "_site/index.html" ]; then
            echo "🔄 Renaming INDEX.html to index.html..."
            cp "_site/INDEX.html" "_site/index.html"
          fi
          
          # Fix unconverted markdown files
          echo "🔧 Handling unconverted markdown files..."
          for md_file in $(find _site -name "*.md"); do
            html_file="${md_file%.md}.html"
            dir_name=$(dirname "$md_file")
            base_name=$(basename "$md_file" .md)
            
            echo "  Converting $md_file to HTML..."
            
            # Create a minimal HTML version of the markdown file
            echo "<html><head><title>$base_name</title>" > "$html_file"
            echo "<meta http-equiv=\"refresh\" content=\"0; url='$base_name'\">" >> "$html_file"
            echo "</head><body>" >> "$html_file"
            echo "<h1>$base_name</h1>" >> "$html_file"
            echo "<p>This page should redirect automatically. If not, <a href=\"$base_name\">click here</a>.</p>" >> "$html_file"
            echo "</body></html>" >> "$html_file"
            
            # Create index.html in a directory with the same name for proper paths
            mkdir -p "$dir_name/$base_name"
            cp "$html_file" "$dir_name/$base_name/index.html"
          done
          
          # Ensure lowercase 'index' directory exists for assets
          if [ -d "_site/INDEX" ]; then
            echo "🔄 Creating lowercase version of INDEX directory..."
            mkdir -p "_site/index"
            cp -r "_site/INDEX/"* "_site/index/" 2>/dev/null || echo "No files to copy (empty directory)"
          fi
          
          # Verification steps
          echo "🔍 Verifying build results..."
          
          # Show root files explicitly
          echo "📄 Files at site root after fixes:"
          ls -la _site/
          
          # Check for HTML files
          echo "✓ HTML files generated from markdown and fixes:"
          find _site -name "*.html" | grep -v "assets" | head -n 15
          html_count=$(find _site -name "*.html" | wc -l)
          echo "  Total HTML files: $html_count"
          
          # List remaining markdown files (if any)
          md_files=$(find _site -name "*.md" | wc -l)
          if [ "$md_files" -gt 0 ]; then
            echo "⚠️ WARNING: Still found $md_files markdown files in output:"
            find _site -name "*.md" | head -n 10
          else
            echo "✅ No markdown files found in output (good!)"
          fi
          
          # Check for previously failed files
          for check_file in "features/configuration-based/PAGE_TEMPLATES" "features/configuration-based/PAGE_EVENTS" "features/code-based/PAGE_VIEWS"; do
            if [ -f "_site/$check_file.html" ] || [ -d "_site/$check_file" ]; then
              echo "✅ Successfully handled: $check_file"
            else
              echo "❌ FAILED to handle: $check_file"
            fi
          done
          
          # Final output structure
          echo "📊 Final site structure:"
          find _site -type f | grep -e "index.html" -e "features" | sort | head -n 15
          echo "... (and more files)"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          timeout: 600000 # 10 minutes in milliseconds